version: '3.7'

services:

  web:
    container_name: car_web
    build: 
      context: . # build the the docker image[Dockerfile] that's in the current directory
      target: production # build only production section of the docker image
    ports:
      - 9229:9229 # host_port:container_port should be in sync
      - 3000:3000
    command: npm run start:prod
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PRODUCTION: 'true'
    env_file:
      - .env # calling the .env file
    depends_on:
      - postgres
      - mongo
  
  postgres:
    container_name: car_postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      # POSTGRES_HOST: ${DB_HOST}
    ports:
      - 5432:5432

  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin


  mongo:
    container_name: car_mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGOROOTUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOROOTPASSWD}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    ports: 
      - '27017-27019:27017-27019'

  
  # redis:
  #   image: redis:7.0.0-alpine
  #   restart: always
  #   command: redis-server
  #   ports:
  #     - "6379:6379"
