version: '3.7'

services:

  web:
    container_name: car_web
    build: 
      context: . # build the the docker image[Dockerfile] that's in the current directory
      target: development # build only development section of the docker image
    ports:
      - 9229:9229 # host_port:container_port should be in sync
      - 3000:3000
    command: npm run start:dev
    environment:
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: 'development'
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_REFRESH_TOKEN: ${OAUTH_REFRESH_TOKEN}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}

    volumes:
      - .:/usr/src/app # mounting the current directory inside the container
      - /usr/src/app/node_modules # mounting node_modules inside the container
    env_file:
      - .env # calling the .env file
    depends_on:
      - postgres
      - mongo
  
  postgres:
    container_name: car_postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${RDS_USERNAME}
      POSTGRES_PASSWORD: ${RDS_PASSWORD}
      POSTGRES_DB: ${RDS_DB_NAME}
      POSTGRES_HOST: ${RDS_HOSTNAME}
      POSTGRES_PORT: ${RDS_PORT}

    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./var/lib/pgadmin

  mongo:
    container_name: car_mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGOROOTUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOROOTPASSWD}
    
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./mongo-volume:/data/db
    ports: 
      - '27017-27019:27017-27019'

  
  # redis:
  #   image: redis:7.0.0-alpine
  #   restart: always
  #   command: redis-server
  #   ports:
  #     - "6379:6379"
volumes:
  pgdata: